CREATE TABLE DINE_VOUCHER (
	VID INT PRIMARY KEY,
	CashDiscount DECIMAL(10, 2),
	UID INT,
	DateTime DATETIME,
	DateIssued DATE,
	ExpiryDate DATE,
	Description VARCHAR(255),
	Status VARCHAR(20),
	FOREIGN KEY (UID) REFERENCES USER_ACC(UID)
);